# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: username
  password: password
  host: <%= ENV['IP'] %>
  

development:
  <<: *default
  database: ideator_development
  
test:
  <<: *default
  database: ideator_test
  
production:
  <<: *default
  database: ideator_production
